config/routes.rb
Rails.application.routes.draw do
  root 'lunches#index'
  devise_for :users
  resources :lunches, only: [:index, :show, :create, :new, :delete] do
    resources :groups
  end
end

app/models/group.rb
class Group < ActiveRecord::Base

  validates_presence_of :user_id, :lunch_id
  validates_uniqueness_of :user_id, scope: :lunch_id, message: "is already in this group!"

  belongs_to :lunch
  belongs_to :user

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base

validates_presence_of :name, :price, :date, :time

  CATEGORIES = %w[¯\\_(ツ)_/¯ italian american seafood sushi chinese thai vietnamese desserts bakery japanese hamburgers cajun pizza other]
  validates :category, inclusion: { in: CATEGORIES, allow_blank: true }

  PRICES = %w[$ $$ $$$ $$$$ $$$$$]
  validates :price, inclusion: { in: PRICES }

  has_many :groups
  has_many :users,
    through: :groups
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups
  has_many :lunches,
    through: :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
  end

  def create
    @lunch = Lunch.find(params[:lunch_id].to_i)
    @group = Group.new(lunch_id: @lunch.id, user_id: current_user.id)
    # @lunch.users << current_user
    # current_user.lunches << @lunch

    if @group.save
      flash[:notice] =  'Lunch joined!'
      redirect_to lunches_path
    else
      flash[:alert] = @group.errors.full_messages.join(", ")
      redirect_to lunches_path
    end
  end

  protected
   def group_params
    params.require(:group).permit(:user_id, :lunch_id)
   end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController

  def index
     @lunches = Lunch.where("date > current_timestamp - (20 * interval '1 minute')").order(:date, :time)
  end

  def new
    @lunch = Lunch.new
    @categories = Lunch::CATEGORIES
    @prices = Lunch::PRICES
  end

  def create
		@lunch = Lunch.new(lunch_params )
    @lunch.date = params[:date]
    @lunch.time = params[:time]
		if @lunch.save
			flash[:notice] =  'Lunch Successfully Added!'
			redirect_to @lunch
		else
			flash[:error] = @lunch.errors.full_messages.join(". ")
			render :new
		end
	end

  def show
    @user = current_user
    @lunch = Lunch.find(params[:id].to_i)
  end

  protected
   def lunch_params
    params.require(:lunch).permit(:location, :description, :category, :price, :date, :time, :name)
   end

end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
   <% if msg.is_a?(String) %>
     <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
   <% end %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LauncherLunches</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">LauncherLunches</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%= render "layouts/flash" %>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/lunches/index.html.erb
<div class='row text-center'>
  <h2>List of Lunches</h2>
  <div class="row panel small-6 columns small-centered">
   <% @lunches.each do |lunch| %>
    <div class="small-9 columns small-centered">
      <article class="event">

          <div class="event-date">
          <p class="event-month"><%=lunch.date.strftime("%b")%></p>
          <p class="event-day"><%=lunch.date.strftime("%d")%></p>
          </div>

          <div class="event-desc">
            <h4 class="event-desc-header"> <%=lunch.name%></h4>
            <p class="event-desc-detail"><span class="event-desc-time"></span><%=lunch.category%> - <%=lunch.time.strftime("%l:%M%p")%> </p>
            <%= link_to "Details", lunch_path(lunch), class:"success button" %>
          </div>

        </article>
       <hr>
    </div>
  </div>
   <% end %>
   <br>
   <br>
   <br>
   <%= link_to "Add a new Lunch", new_lunch_path, class:"success button expand"%>
</div>

app/views/lunches/new.html.erb
<div class='row text-center'>

  <h1>Add a Lunch </h1>

  <%= form_for @lunch do |f| %>
  <div class="large-9 large-centered columns panel">
    <div class="login-box">
      <div class="row">
        <div class="large-12 columns">
           <%= f.label :name_of_group %>
           <%= f.text_field :name %>
           <br>

            <%= label_tag(:date, "Date:") %>
            <%= date_field_tag(:date) %>
           <br>
            <%= label_tag(:date, "Time to meet at door:") %>
            <%= time_field_tag(:time) %>
           <br>
           <%= f.label :price_range %>
           <%= f.select :price, @prices%>
           <br>
            Optional Fields
           <br><br>
           <%= f.label :location %>
           <%= f.text_field :location %>
           <br>
           <%= f.label :category %>
           <%= f.select :category, @categories%>
           <br>
           <%= f.label :description %>
           <%= f.text_field :description %>

           <%= f.submit "Add Lunch Group", class: 'button small' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lunches/show.html.erb
<br>
<div class="search-results">
      <div class="row ">
        <div class="large-10 columns">
          <div class="row">
            <div class=" large-9 columns">
              <h5><a href="#">  <%=@lunch.name%>  </a></h5>
              <p><%= @lunch.date.strftime("%A, %m/%d ") %> | <%= @lunch.time.strftime("Meet at the door at %l:%M%p")%></p>
            </div>
            <div class=" large-3 columns">
              <%= link_to 'Join', lunch_groups_path(@lunch), method: :post, class: "button alert" %>
            </div>
            <div class="row">
              <div class=" large-12 columns">
                <ul class="large-block-grid-2">
                  <li>
                    <ul>
                      <li><strong>Category: </strong><%= @lunch.category %></li>
                      <li><strong>Description:</strong> <%= @lunch.description %> </li>
                    </ul>
                  </li>
                  <li>
                    <ul>
                      <li><strong>Price:</strong> <%= @lunch.price %>  </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="small-12 columns">
                <ul class="large-block-grid-2">
                  <h3>Attending Launchers:</h3>
                  <% @lunch.users.each do |user| %>
                  <li><%= user.email %> </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

<br>
<br>
<br>

<%= link_to "List of Lunches", lunches_path %>